DROP TABLE IF EXISTS USERGROUPS CASCADE;
DROP TABLE IF EXISTS ACREDENTIALS CASCADE;
DROP TABLE IF EXISTS AUSER CASCADE;
DROP TABLE IF EXISTS CONTACT CASCADE;
DROP TABLE IF EXISTS EGENDER CASCADE;
DROP TABLE IF EXISTS ETITLE CASCADE;
DROP TABLE IF EXISTS EDOMAIN CASCADE;
DROP TABLE IF EXISTS EGROUP CASCADE;
DROP TABLE IF EXISTS EMETHOD CASCADE;

CREATE TABLE EGENDER (
	GID VARCHAR(128) PRIMARY KEY
);
INSERT INTO EGENDER (GID) VALUES ('Male');
INSERT INTO EGENDER (GID) VALUES ('Female');

CREATE TABLE ETITLE (
	TID VARCHAR(128) PRIMARY KEY,
	TLABEL VARCHAR(128) NOT NULL
);
INSERT INTO ETITLE (TID, TLABEL) VALUES ('Mr', 'Mr');
INSERT INTO ETITLE (TID, TLABEL) VALUES ('Mrs', 'Mrs');
INSERT INTO ETITLE (TID, TLABEL) VALUES ('Ms', 'Ms');
INSERT INTO ETITLE (TID, TLABEL) VALUES ('Dr', 'Dr');

CREATE TABLE EDOMAIN (
	DID VARCHAR(128) PRIMARY KEY,
	DLABEL VARCHAR(128) NOT NULL
);
INSERT INTO EDOMAIN (DID, DLABEL) VALUES ('NUVERSITY', 'NUVERSITY');

CREATE TABLE EGROUP (
	GID VARCHAR(128) PRIMARY KEY,
	GLABEL VARCHAR(128) NOT NULL
);
INSERT INTO EGROUP (GID, GLABEL) VALUES ('APPLICANT', 'APPLICANT');
INSERT INTO EGROUP (GID, GLABEL) VALUES ('STUDENT', 'STUDENT');
INSERT INTO EGROUP (GID, GLABEL) VALUES ('TEACHER', 'TEACHER');
INSERT INTO EGROUP (GID, GLABEL) VALUES ('DEAN', 'DEAN');
INSERT INTO EGROUP (GID, GLABEL) VALUES ('COORDINATOR', 'COORDINATOR');
INSERT INTO EGROUP (GID, GLABEL) VALUES ('MGMT', 'MGMT');
INSERT INTO EGROUP (GID, GLABEL) VALUES ('ADMIN', 'ADMIN');


CREATE TABLE CONTACT (
	EMAIL VARCHAR(128) PRIMARY KEY,
	FIRSTNAME VARCHAR(128) NOT NULL,
	MIDDLENAME VARCHAR(128),
	LASTNAME VARCHAR(128) NOT NULL,
	DOB TIMESTAMP NOT NULL,
	GENDER VARCHAR(32) NOT NULL,
	TITLE VARCHAR(32) NOT NULL,
	PHONE VARCHAR(128),
	CADDRESS VARCHAR(256),
	PHOTO VARCHAR(128),
	CONSTRAINT FK_CTT_GDR
      FOREIGN KEY(GENDER) 
	  REFERENCES EGENDER(GID),
	CONSTRAINT FK_CTT_TTL
      FOREIGN KEY(TITLE) 
	  REFERENCES ETITLE(TID)
);

CREATE TABLE AUSER (
	USERID VARCHAR(128) PRIMARY KEY,
	CONTACTID VARCHAR(128) NOT NULL,
	NUMAIL VARCHAR(128) NOT NULL,
	JOINING_DATE TIMESTAMP NOT NULL,
	DOMAINID VARCHAR(128),
	CONSTRAINT FK_USR_CTT
      FOREIGN KEY(CONTACTID) 
	  REFERENCES CONTACT(EMAIL),
	CONSTRAINT FK_USR_DOMAIN
      FOREIGN KEY(DOMAINID) 
	  REFERENCES EDOMAIN(DID)
);
CREATE UNIQUE INDEX NUMAIL_IDX on AUSER(NUMAIL);

CREATE TABLE USERGROUPS (
	EID VARCHAR(128) PRIMARY KEY,
	USRID VARCHAR(128) NOT NULL,
	GRPID VARCHAR(128) NOT NULL,
	CONSTRAINT FK_USRGRP_UID
      FOREIGN KEY(USRID) 
	  REFERENCES AUSER(USERID),
	CONSTRAINT FK_USRGRP_GID
      FOREIGN KEY(GRPID) 
	  REFERENCES EGROUP(GID)
);

CREATE TABLE EMETHOD (
	MTDID VARCHAR(128) PRIMARY KEY,
	MTDLABEL VARCHAR(128) NOT NULL
);

INSERT INTO EMETHOD(MTDID, MTDLABEL) VALUES('PASSWORD', 'PASSWORD');
INSERT INTO EMETHOD(MTDID, MTDLABEL) VALUES('FACE ID', 'FACE ID');

CREATE TABLE ACREDENTIALS (
	CRED_ID VARCHAR(128) PRIMARY KEY,
	CMETHOD VARCHAR(128) NOT NULL,
	LOGINID VARCHAR(128) NOT NULL,
	PWDDATA VARCHAR(256) NOT NULL,
	EXPIRE_BY TIMESTAMP NOT NULL,
	TRY_COUNT INT NOT NULL,
	BLOCKED BOOLEAN NOT NULL,
	CONSTRAINT FK_CRD_MTD
      FOREIGN KEY(CMETHOD) 
	  REFERENCES EMETHOD(MTDID)
);
